### ISSUE TITLE
Add quiet (`-q`) flag

### ISSUE THREAD

**Issue by DDtKey** [derlin/bitdowntoc#27]
After upgrading `bitdowntoc` version to `2.0.0` I noticed that it started to produce additional output to stdout, e.g:

```
Generating TOC with params: Params(...)
```

It would be nice to be able to control this behavior, for the cases when I need to use the result of `bitdowntoc`  in pipe

**Comment by derlin** [comment]
This is a good point, thanks for reporting!

In the meantime, it is possible to avoid pipes and use the `-o` flag to write to a file, or the `-i` to do it inline.

**Comment by DDtKey** [comment]
Yes, definitely. So I consider this more like a feature request. 

Especially considering that this change was in a major update (in accordance with semver)
