### ISSUE TITLE
add to homebrew package manager (macOS)

### ISSUE THREAD

**Issue by 0xdevalias** [derlin/bitdowntoc#34]
Suggestion: Addition of bitdowntoc to Homebrew Package Manager for macOS

Homebrew is a prominent package manager for macOS, streamlining the installation, update, and management of software. Including bitdowntoc in Homebrew would enhance accessibility and convenience for macOS users.

Benefits:
- Simplified installation process with a single command: `brew install bitdowntoc`.
- Automated updates managed by Homebrew.
- Increased exposure among macOS users.

Requirements:

To integrate bitdowntoc with Homebrew, a Homebrew formula needs to be developed and submitted. Relevant resources include:

- Homebrew Formula Documentation: https://docs.brew.sh/Formula-Cookbook
- Homebrew Contribution Guidelines: https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md

**Comment by derlin** [comment]
Glad you asked, this is on my TODO list for a while now :)
Will dig into this as soon as I find some time!

**Comment by 0xdevalias** [comment]
Amazing, thankyou!

**Comment by derlin** [comment]
Here is the pull request: https://github.com/Homebrew/homebrew-core/pull/170216 

🤞🤞

**Comment by derlin** [comment]
Created a tap here: https://github.com/derlin/homebrew-bitdowntoc

You can now install bitdowntoc by running:
```bash
brew install derlin/bitdowntoc/bitdowntoc
```

I have updated the README accordingly.

Thanks for the issue, and let's hope this repo will get notable enough at some point  😉

**Comment by 0xdevalias** [comment]
Awesome, thanks for that!
