### ISSUE TITLE
Bug when title above TOC and subheading after it have the same text

### ISSUE THREAD

**Issue by 0xdevalias** [derlin/bitdowntoc#45]
I just noticed that when passing the text of this gist through the TOC generator, the TOC link for the 'Generating Synth Patches with AI' link is wrong, as it links to the title, rather than the subheading:

- https://gist.github.com/0xdevalias/5a06349b376d01b2a76ad27a86b08c1b

For most other links, when there is a duplicate, it correctly calculates the anchor to be used (eg. `unsorted`, `unsorted-1`, etc); but in this instance, I assume that it is probably ignoring the main heading (since it is before the TOC), and thus not properly accounting for it when calculating the anchors.

So instead of linking to `#generating-synth-patches-with-ai`, it really should be going to `#generating-synth-patches-with-ai-1`

(I pretty much exclusively use https://derlin.github.io/bitdowntoc/ , so if/when this gets fixed and pushed there, that would be awesome!)

**Comment by derlin** [comment]
Very good catch, thank you for the report @0xdevalias !
I am on it 🙂

**Comment by 0xdevalias** [comment]
> I am on it 🙂

@derlin Thank You, appreciate it! :)

**Comment by derlin** [comment]
@0xdevalias The fix is live on  https://derlin.github.io/bitdowntoc/, let me know if you still encounter any issue.

**Comment by 0xdevalias** [comment]
@derlin Just tried it out, the diff seems to confirm that it fixes the issue; Thanks :)

- https://gist.github.com/0xdevalias/5a06349b376d01b2a76ad27a86b08c1b/revisions#diff-5f192744f3f1bac92f5fdf816368ab4be285a8f5d6c10a82702717342bf1f72b
