### ISSUE TITLE
Missing TOC end causes parsing to fail

### ISSUE THREAD

**Issue by maurymarkowitz** [derlin/bitdowntoc#49]
I had a document that still had a `<!-- TOC start` but the matching `<!-- TOC end` was missing for some reason. In this case, Generate produces no output.

I believe this should report an error. Alternately, the next `<!-- TOC -->` might be used to indicate the end, in the same fashion as one `<p>` intrinsically closes another.

**Comment by derlin** [comment]
Thank you for reporting this issue.

This seems like a corrupted document. The same may happen if the markdown is malformed (e.g. missing end of code block). I am not sure I want to go into the rabbit hole of reporting every corruption.

In this instance, though, I agree that it would make sense to warn the user in case of a missing toc marker end. I will see what I can do.

**Comment by maurymarkowitz** [comment]
If it is straightforward, looking for a missing TOC start before a TOC end would likely be useful too.
